# Definition: FlippyConfiguration
# Hash: cea61f0c
# Flags: 0x30a

0x0: tLootBeams # DT_FIXEDARRAY [5 array size] => LootBeamEffects
0x3c: tUniqueLootBeam # LootBeamEffects
0x48: tSetLootBeam # LootBeamEffects
0x54: snoPickupEffects # DT_FIXEDARRAY (32 bits used) [5 array size] {group 0xe "EffectGroup"} => DT_SNO
0x68: snoUniquePickupEffect # DT_SNO (32 bits used) {group 0xe "EffectGroup"}
0x6c: snoSetPickupEffect # DT_SNO (32 bits used) {group 0xe "EffectGroup"}
0x70: snoLandSoundEffects # DT_FIXEDARRAY (32 bits used) [5 array size] {group 0x28 "Sound"} => DT_SNO
0x84: snoGreaterAffixLandSoundEffect # DT_SNO (32 bits used) {group 0x28 "Sound"}
0x88: snoUniqueLandSoundEffect # DT_SNO (32 bits used) {group 0x28 "Sound"}
0x8c: snoSetLandSoundEffect # DT_SNO (32 bits used) {group 0x28 "Sound"}
0x90: null or eof # DT_NULL
