# Definition: UIDateTimeSettings
# Hash: b2d29bdc
# Flags: 0x302

0x0: nDateTimeUTC # DT_INT64 (64 bits used)
0x8: eDateTimeDateFormat # DT_ENUM (32 bits used)
0xc: eDateTimeTimeFormat # DT_ENUM (32 bits used)
0x10: eStyle # DT_ENUM (32 bits used)
0x18: null or eof # DT_NULL
